price_per_court: 27

# Time must be in "HH:MM" 24-hour format (i.e. "09:00", not "9:00").
# If a day is set to null, no booking will be made on that day.
# If a day has a start and end time, a booking will be made within that time range.
# If a day has a start time and no end time, the end time will default to "23:00".
# If a day has no start time and an end time, the start time will default to "06:00".
# 3 variables per day: start, end, location.
# Location is not mandatory. If not provided, the location will default to "bond_crescent".
schedule:
  monday: null
  tuesday:
    start: "09:00"
    end: "13:00"
  wednesday:
    start: "19:00"
    end: "21:00"
  thursday: null
  friday:
    start: "16:00"
    end: "18:00"
    location: "corinthian_drive"
  saturday:
    start: "09:00"
    end: "19:00"
    location: "corinthian_drive"
  sunday:
    start: "10:00"
    end: "19:00"
