from user import login, logout, fetch_user_detail
from booking import book_court, fetch_court_availability, identify_available_courts

TEST_DATA = {
    "1": {
        "court": {"id": 1, "name": "Court 1"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Booked",
                "user_name": "007149",
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "Sch Event",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "005807",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "005807",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Booked",
                "user_name": "001640",
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "2": {
        "court": {"id": 2, "name": "Court 2"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "Sch Event",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "008160",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "008160",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Booked",
                "user_name": "008160",
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "3": {
        "court": {"id": 3, "name": "Court 3"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "Sch Event",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "005144",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "005144",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Booked",
                "user_name": "005144",
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "4": {
        "court": {"id": 4, "name": "Court 4"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Booked",
                "user_name": "Senior SQD",
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "Senior SQD",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Booked",
                "user_name": "Over 55s",
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "Sch Event",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "008077",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "006974",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Booked",
                "user_name": "006974",
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "5": {
        "court": {"id": 5, "name": "Court 5"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Booked",
                "user_name": "002141",
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Booked",
                "user_name": "Senior SQD",
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "Senior SQD",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "NS MidWeek",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "001757",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "006004",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Booked",
                "user_name": "006004",
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "Sch Event",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "002524",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "002336",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Booked",
                "user_name": "001584",
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Booked",
                "user_name": "001584",
            },
        ],
    },
    "6": {
        "court": {"id": 6, "name": "Court 6"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Booked",
                "user_name": "BNHPlayerD",
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Booked",
                "user_name": "Senior SQD",
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "Senior SQD",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "N H Club",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "N H Club",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "007280",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Booked",
                "user_name": "005202",
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Booked",
                "user_name": "005202",
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "Sch Event",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "002336",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "007723",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "7": {
        "court": {"id": 7, "name": "Court 7"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Booked",
                "user_name": "BNZ",
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "BNZ",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "N H Club",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "N H Club",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "009371",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "Sch Event",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "006457",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "006457",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Booked",
                "user_name": "008295",
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Booked",
                "user_name": "008295",
            },
        ],
    },
    "8": {
        "court": {"id": 8, "name": "Court 8"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Booked",
                "user_name": "BNZ",
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "BNZ",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "001757",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "004441",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "008733",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "008271",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "008386",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "008386",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "9": {
        "court": {"id": 9, "name": "Court 9"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "North 3040",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "North 3040",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Booked",
                "user_name": "009314",
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "009314",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Booked",
                "user_name": "008371",
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Booked",
                "user_name": "008371",
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "006493",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "002347",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "002347",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Booked",
                "user_name": "002347",
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "10": {
        "court": {"id": 10, "name": "Court 10"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "North 3040",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "North 3040",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Booked",
                "user_name": "002760",
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "005773",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "003827",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "001652",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
    "11": {
        "court": {"id": 11, "name": "Court 11"},
        "timetable": [
            {
                "start_time": "06:00",
                "end_time": "07:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "07:00",
                "end_time": "08:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "08:00",
                "end_time": "09:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "09:00",
                "end_time": "10:00",
                "status": "Booked",
                "user_name": "001991",
            },
            {
                "start_time": "10:00",
                "end_time": "11:00",
                "status": "Booked",
                "user_name": "North 3040",
            },
            {
                "start_time": "11:00",
                "end_time": "12:00",
                "status": "Booked",
                "user_name": "North 3040",
            },
            {
                "start_time": "12:00",
                "end_time": "13:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "13:00",
                "end_time": "14:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "14:00",
                "end_time": "15:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "15:00",
                "end_time": "16:00",
                "status": "Booked",
                "user_name": "002257",
            },
            {
                "start_time": "16:00",
                "end_time": "17:00",
                "status": "Booked",
                "user_name": "006041",
            },
            {
                "start_time": "17:00",
                "end_time": "18:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "18:00",
                "end_time": "19:00",
                "status": "Booked",
                "user_name": "Dev. SQD",
            },
            {
                "start_time": "19:00",
                "end_time": "20:00",
                "status": "Booked",
                "user_name": "005183",
            },
            {
                "start_time": "20:00",
                "end_time": "21:00",
                "status": "Booked",
                "user_name": "002400",
            },
            {
                "start_time": "21:00",
                "end_time": "22:00",
                "status": "Available",
                "user_name": None,
            },
            {
                "start_time": "22:00",
                "end_time": "23:00",
                "status": "Available",
                "user_name": None,
            },
        ],
    },
}


def main():

    print("automated court booker !")

    # print("\n_____LOGIN ATTEMPT_____")
    # session = login()

    # print("\n_____BOOKING ATTEMPT_____")

    # fetch_user_detail(session, "credit_balance")

    # data = fetch_court_availability(session, "bond_crescent")
    identify_available_courts(TEST_DATA)

    # print("\n_____LOGOUT ATTEMPT_____")
    # logout(session)


if __name__ == "__main__":
    main()
